-- Create users table for authentication
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(20) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    enabled NUMBER(1) DEFAULT 1 NOT NULL,
    account_non_expired NUMBER(1) DEFAULT 1 NOT NULL,
    account_non_locked NUMBER(1) DEFAULT 1 NOT NULL,
    credentials_non_expired NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Add indexes
CREATE UNIQUE INDEX idx_users_username ON users(username);

-- Add comments
COMMENT ON TABLE users IS 'Users table for authentication and authorization';
COMMENT ON COLUMN users.id IS 'Primary key for users table';
COMMENT ON COLUMN users.username IS 'Unique username for user authentication';
COMMENT ON COLUMN users.password IS 'Encrypted password using BCrypt';
COMMENT ON COLUMN users.enabled IS 'Whether the user account is enabled (1=yes, 0=no)';
COMMENT ON COLUMN users.account_non_expired IS 'Whether the user account is not expired (1=yes, 0=no)';
COMMENT ON COLUMN users.account_non_locked IS 'Whether the user account is not locked (1=yes, 0=no)';
COMMENT ON COLUMN users.credentials_non_expired IS 'Whether the user credentials are not expired (1=yes, 0=no)';